<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data_interno</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>965b7e83-52d6-4900-9231-4a5b06f6a2ff</testSuiteGuid>
   <testCaseLink>
      <guid>01e5afe5-ead5-4be4-98a3-a33b1a815174</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drive_excel/Drive_excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4d4fef07-0364-4abc-a03a-ac0e95e6a6bf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_excel/Data_interno</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4d4fef07-0364-4abc-a03a-ac0e95e6a6bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>84c8f7ae-af74-469a-9d4f-d89ffefd54ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4d4fef07-0364-4abc-a03a-ac0e95e6a6bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>7118a1bb-c64f-4d2f-8179-76f110f56584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4d4fef07-0364-4abc-a03a-ac0e95e6a6bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>e9c93bbf-5c21-4ccd-b047-bd46d43dee13</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
