<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data_excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>09c2734c-cef6-4a88-a78a-a68c530e29c3</testSuiteGuid>
   <testCaseLink>
      <guid>e01678a6-8e87-4d10-9181-5619ac46b80a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drive_excel/Drive_excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>523785f5-2c6c-4b8c-8007-1ad64b8037dd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_excel/Base_excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>523785f5-2c6c-4b8c-8007-1ad64b8037dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>84c8f7ae-af74-469a-9d4f-d89ffefd54ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>523785f5-2c6c-4b8c-8007-1ad64b8037dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>7118a1bb-c64f-4d2f-8179-76f110f56584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>523785f5-2c6c-4b8c-8007-1ad64b8037dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>e9c93bbf-5c21-4ccd-b047-bd46d43dee13</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
