<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data_csv</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fd82b943-72cb-478e-a6ba-ccc1abaf3731</testSuiteGuid>
   <testCaseLink>
      <guid>cfa874b8-8dc2-4754-a079-4fbc5d45e2e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drive_excel/Drive_excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3b9d12fb-8ae8-4121-a4d9-efe23f97dcaf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_excel/Data_csv</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3b9d12fb-8ae8-4121-a4d9-efe23f97dcaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>84c8f7ae-af74-469a-9d4f-d89ffefd54ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b9d12fb-8ae8-4121-a4d9-efe23f97dcaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>7118a1bb-c64f-4d2f-8179-76f110f56584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b9d12fb-8ae8-4121-a4d9-efe23f97dcaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>e9c93bbf-5c21-4ccd-b047-bd46d43dee13</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
