<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>a27479c5-32ea-4d9c-a919-f21a207c0811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-34</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='wsf-1-field-34']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87a91390-333b-430b-9a16-aeb4e73239d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3a7071db-8383-400a-b87e-62495bc9a99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-34</value>
      <webElementGuid>52cec7e0-e69d-4f1f-a342-ea02d8949df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_34</value>
      <webElementGuid>2045bb14-7286-4173-b6cb-c9cd622fd0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-button wsf-button-full wsf-button-primary</value>
      <webElementGuid>52b7a8b4-66df-477b-80c4-03ad5668d85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>2b4b142b-fa43-4edc-b50a-d7834544f10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>3f518825-0fc0-4788-ad33-a4053016a885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-34&quot;)</value>
      <webElementGuid>b4ff95a2-8555-4a59-87fb-0d998063ab57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='wsf-1-field-34']</value>
      <webElementGuid>69e4abd0-c14d-41f3-b53b-f99eac1d5a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-34']/button</value>
      <webElementGuid>821d6c87-26a1-4ee3-b5e1-48b3463c8f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This checkbox is required.'])[4]/following::button[1]</value>
      <webElementGuid>0239c1f1-8211-4ef2-9fdc-80dca3e72afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This checkbox is required.'])[3]/following::button[1]</value>
      <webElementGuid>00efb894-dd8e-433c-8542-ee057964f662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diseñado por Rodrigo Villanueva Nieto | Todos los Derechos Reservados.'])[1]/preceding::button[1]</value>
      <webElementGuid>328d57c5-e71c-401f-9d18-922c31624265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'wsf-1-field-34', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>77920366-69b7-4be5-b47b-628b488de069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>50d53e7e-bc64-43c1-83a0-ada9994c7ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4352a95a-ccbf-4e96-8406-65c2d3c5c260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'wsf-1-field-34' and @name = 'field_34' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>24fc857a-27b8-4287-b1ea-0d633db87912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
