<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_field_29</name>
   <tag></tag>
   <elementGuidId>85ac2a58-a1ae-49a5-859e-ddb35e2b1977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c26a6ea-01a3-42ff-9139-57257cc0c306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>472ff682-ab44-49e2-ace5-8c232a580630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-29</value>
      <webElementGuid>d54b8ec1-4a21-4782-b14f-177b37f66b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_29</value>
      <webElementGuid>1296e963-db30-4829-9b58-bcb32bb31652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre:</value>
      <webElementGuid>c8a9f2af-50c0-4d20-a3ca-e703635dcab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field nombre nom</value>
      <webElementGuid>d379d602-ff9f-43c5-bb1b-4036b31d5cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-29</value>
      <webElementGuid>2ac966d3-cb24-4aa3-a964-962c85673789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-29&quot;)</value>
      <webElementGuid>0057e992-f15e-4943-a31b-0bac65fe0563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-29']</value>
      <webElementGuid>10e8190e-4143-43be-a686-fac3824b8071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-29']/input</value>
      <webElementGuid>5829aa7a-83ce-450a-a81b-3393d91eda13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ba80da8b-1727-48e9-9fee-b5b863f9180b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wsf-1-field-29' and @name = 'field_29' and @placeholder = 'Nombre:']</value>
      <webElementGuid>ab096ff5-6c00-4efe-a3ef-60574ac56274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
