<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_field_30</name>
   <tag></tag>
   <elementGuidId>a04f903c-c757-4bcd-93b7-2d09bf4e7457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5679f5dd-5943-43be-84c1-8692a051d03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c977e75d-db0a-4288-9f06-9255fde55aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-30</value>
      <webElementGuid>bb149083-469a-4f4f-8983-d0ee032a4196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_30</value>
      <webElementGuid>a81f1b82-0523-4808-9d1b-c491592f8d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>010928b1-a938-4c74-b920-c70418ab1bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>a64bc65c-8d53-4f20-bd1b-bf2b9fa67ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-30</value>
      <webElementGuid>7bbacd73-a1ae-4600-8e0f-3e9edd190c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-30&quot;)</value>
      <webElementGuid>78ee2011-44ec-4a57-8252-47b96dfb6882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-30']</value>
      <webElementGuid>8f6a97eb-95f5-4935-a44e-25b36bcc346e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-30']/input</value>
      <webElementGuid>2b286e4f-dbeb-47b2-9399-acaa313e473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f9d7687e-05a4-46b3-914b-5ae16a140b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wsf-1-field-30' and @name = 'field_30' and @placeholder = 'Apellidos']</value>
      <webElementGuid>8ba0f54b-8cf4-4ab2-8ea2-52c7f937c18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
