<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_JS</name>
   <tag></tag>
   <elementGuidId>59baf971-6fe5-49e0-bd06-bc06caa046e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-label-36-row-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='wsf-1-label-36-row-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7e145dfc-f7af-48b8-9e12-735632d240d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-label-36-row-3</value>
      <webElementGuid>f77342e2-baca-4fc5-933b-5159b0537ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>wsf-1-field-36-row-3</value>
      <webElementGuid>7876a6dc-370c-42a4-9bfc-5bac782de017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-label</value>
      <webElementGuid>e2d1d972-a296-4f17-ba5f-d601a6cc6707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JS</value>
      <webElementGuid>078dd803-aca1-46af-8f4b-95b51d06fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-label-36-row-3&quot;)</value>
      <webElementGuid>64fc70c7-1b5c-4983-b736-c918e160b0a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='wsf-1-label-36-row-3']</value>
      <webElementGuid>bdcd88a5-3364-44d5-8e29-66ab8813bc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-36']/div/div[3]/label</value>
      <webElementGuid>b87ae1f2-b1e4-4b82-9288-6ed91fefe1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This checkbox is required.'])[2]/following::label[1]</value>
      <webElementGuid>ae0032a9-00f9-426b-8e3f-f032130e811a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PYTHON'])[1]/following::label[1]</value>
      <webElementGuid>b717739c-e649-4723-b119-da69c895338a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This checkbox is required.'])[3]/preceding::label[1]</value>
      <webElementGuid>13362fb5-a50b-4f4d-a645-465b4cc66833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This checkbox is required.'])[4]/preceding::label[1]</value>
      <webElementGuid>35f266bf-647b-4370-9872-1111896636df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JS']/parent::*</value>
      <webElementGuid>eaa4df9a-135c-4829-90df-c8ea35ede994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/label</value>
      <webElementGuid>76d2dc1e-e1ce-4a06-a5b2-a09012e98852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'wsf-1-label-36-row-3' and (text() = 'JS' or . = 'JS')]</value>
      <webElementGuid>ee3240a1-313d-41b8-a24e-b6fd9ab54b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
