<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Direccin_field_33</name>
   <tag></tag>
   <elementGuidId>3d5f2549-2988-4012-9aa0-ecdca25e495e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wsf-1-field-33']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>60d68195-cefa-4ac5-9080-ec16140b57f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-33</value>
      <webElementGuid>66f41229-6e54-4f45-9aa6-b805a88acc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_33</value>
      <webElementGuid>015804da-f09d-4b6d-86fa-dd7a3785922f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f53f6e5f-9271-4e3a-b885-bc9eb5ead754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textarea-toolbar</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>bd4e3e37-833f-4601-9da7-31caa3a7d310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>adb25edd-6888-4c52-bb69-b5b1b985e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>wsf-1-help-33</value>
      <webElementGuid>2e7c4591-e886-4159-9419-cf3b845dcd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-33</value>
      <webElementGuid>c64cf303-a5fa-4dc1-b840-c8f41eb7f9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-33&quot;)</value>
      <webElementGuid>9ef30c4c-9edf-4be1-aac3-c9ae4ecbd65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wsf-1-field-33']</value>
      <webElementGuid>36755ca3-e39c-41fb-a77a-3637d0aef4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-33']/textarea</value>
      <webElementGuid>027d8d2f-bec6-4b7f-b25c-b86a73533eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5892536c-3081-42e7-8dc8-e712e70e9465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wsf-1-field-33' and @name = 'field_33' and @placeholder = 'Email']</value>
      <webElementGuid>e08a5448-cb97-4460-8b4f-9542b115550c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
